version: '3.7'

networks:
  world:

services:
  nginx:
    image: nginx:1.18.0-alpine
    container_name: nginx-world
    environment:
      TZ: Europe/Kiev
    ports:
      - "8089:8089"
    volumes:
      - ./sources/world:/var/www/world
      - ./config/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - world
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php:
    build:
      context: ./containers
      dockerfile: php8.1-fpm-Dockerfile
    container_name: php81-fpm-world
    environment:
      TZ: Europe/Kiev
    volumes:
      - ./sources/world:/var/www/world
      - ./config/php8/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    ports:
      - "9001:9000"
    networks:
      - world
    extra_hosts:
      - "host.docker.internal:host-gateway"

  queue:
    build:
      context: ./containers
      dockerfile: php8.1-cli-composer-Dockerfile
    container_name: queue-world
    restart: unless-stopped
    command:  ["php", "/var/www/world/artisan", "queue:work"]
    environment:
      TZ: Europe/Kiev
    depends_on:
      - redis
    volumes:
      - ./sources/world:/var/www/world
    networks:
      - world

  composer:
    build:
      context: ./containers
      dockerfile: php8.1-cli-composer-Dockerfile
    container_name: composer-world
    volumes:
      - ./sources/world:/var/www/world
    environment:
      TZ: Europe/Kiev
    working_dir: /var/www/world
    entrypoint: ["composer"]
    depends_on:
      - php
    networks:
      - world

  npm:
    image: node:14.3
    container_name: npm-world
    environment:
      TZ: Europe/Kiev
    volumes:
      - ./sources/world:/var/www/world
    working_dir: /var/www/world
    entrypoint: ["npm"]
    networks:
      - world

  artisan:
    build:
      context: ./containers
      dockerfile: php8.1-cli-composer-Dockerfile
    container_name: artisan-world
    environment:
      TZ: Europe/Kiev
    volumes:
      - ./sources/world:/var/www/world
    working_dir: /var/www/world
    entrypoint: ["php", "/var/www/world/artisan"]
    networks:
      - world

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    command: ["redis-server"]
    environment:
      TZ: Europe/Kiev
    container_name: redis-world
    networks:
      - world