version: '3.7'

networks:
  svit:

services:
  nginx:
    image: nginx:1.18.0-alpine
    container_name: nginx-svit
    environment:
      TZ: Europe/Kiev
    ports:
      - "8089:8089"
    volumes:
      - ./sources/svit:/var/www/svit
      - ./config/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - svit
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php:
    build:
      context: ./containers
      dockerfile: php8.1-fpm-Dockerfile
    container_name: php81-fpm-svit
    environment:
      TZ: Europe/Kiev
    volumes:
      - ./sources/svit:/var/www/svit
      - ./config/php8/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    ports:
      - "9001:9000"
    networks:
      - svit
    extra_hosts:
      - "host.docker.internal:host-gateway"

  queue:
    build:
      context: ./containers
      dockerfile: php8.1-cli-composer-Dockerfile
    container_name: queue-svit
    restart: unless-stopped
    command:  ["php", "/var/www/svit/artisan", "queue:work"]
    environment:
      TZ: Europe/Kiev
    depends_on:
      - redis
    volumes:
      - ./sources/svit:/var/www/svit
    networks:
      - svit

  composer:
    build:
      context: ./containers
      dockerfile: php8.1-cli-composer-Dockerfile
    container_name: composer-svit
    volumes:
      - ./sources/svit:/var/www/svit
    environment:
      TZ: Europe/Kiev
    working_dir: /var/www/svit
    entrypoint: ["composer"]
    depends_on:
      - php
    networks:
      - svit

  npm:
    image: node:14.3
    container_name: npm-svit
    environment:
      TZ: Europe/Kiev
    volumes:
      - ./sources/svit:/var/www/svit
    working_dir: /var/www/svit
    entrypoint: ["npm"]
    networks:
      - svit

  artisan:
    build:
      context: ./containers
      dockerfile: php8.1-cli-composer-Dockerfile
    container_name: artisan-svit
    environment:
      TZ: Europe/Kiev
    volumes:
      - ./sources/svit:/var/www/svit
    working_dir: /var/www/svit
    entrypoint: ["php", "/var/www/svit/artisan"]
    networks:
      - svit

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    command: ["redis-server"]
    environment:
      TZ: Europe/Kiev
    container_name: redis-svit
    networks:
      - svit